server:
  port: 8086

spring:
  application:
    name: evcs-tenant
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:evcs_mgr}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Tenant
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0
          max-wait: 2000ms
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    virtual-host: ${RABBIT_VHOST:/}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.evcs.tenant.entity

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.evcs.tenant.mapper: debug
    com.evcs.common.tenant: debug
    org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

evcs:
  tenant:
    enabled: true
    tenant-id-column: tenant_id
    ignore-tables:
      - sys_tenant
      - sys_user
      - sys_role
      - sys_permission
    default-tenant-id: 1
