server:
  port: 8083

spring:
  application:
    name: evcs-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:evcs_mgr}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Order
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 2
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0
          max-wait: 2000ms
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    virtual-host: ${RABBIT_VHOST:/}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.evcs.order.entity

logging:
  level:
    com.evcs.order: info
    com.evcs.order.mapper: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

billing:
  tou:
    enabled: false
    peak_start: 06:00
    peak_end: 22:00
    peak_price: 1.50
    offpeak_price: 0.80
  service_fee: 0.00
  price_per_kwh: 1.00

evcs:
  tenant:
    enabled: true
    tenant-id-column: tenant_id
    ignore-tables:
      - sys_tenant
      - sys_user
      - sys_role
      - sys_permission
    default-tenant-id: 1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
