server:
  port: 8086

spring:
  application:
    name: evcs-tenant
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:evcs_mgr}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Tenant
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0
          max-wait: 2000ms
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    virtual-host: ${RABBIT_VHOST:/}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.evcs.tenant.entity

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.evcs.tenant.mapper: debug
    com.evcs.common.tenant: debug
    org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Knife4j API文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: EVCS Manager API
    description: 电动汽车充电站管理系统 - 租户管理服务
    version: 2.0.0
    contact:
      name: EVCS Manager Team
      email: support@evcs-manager.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-reload-cache-parameter: true
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: localhost:8086
    enable-home-custom: false
    home-custom-path: classpath:markdown/home.md
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2025 EVCS Manager
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  cors: false
  production: false
  basic:
    enable: false
    username: admin
    password: 123456

evcs:
  tenant:
    enabled: true
    tenant-id-column: tenant_id
    ignore-tables:
      - sys_tenant
      - sys_user
      - sys_role
      - sys_permission
    default-tenant-id: 1
