apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-jar-pvc
  namespace: evcs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
  namespace: evcs
spec:
  containers:
  - name: helper
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /mnt
      name: jar-volume
  volumes:
  - name: jar-volume
    persistentVolumeClaim:
      claimName: payment-jar-pvc
