-- auth 服务 H2 测试表（内部统计端点测试用，仅保留被测表的最小结构）
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    login_identifier VARCHAR(100),
    password VARCHAR(100),
    real_name VARCHAR(50),
    phone VARCHAR(20),
    email VARCHAR(100),
    avatar VARCHAR(500),
    gender INTEGER DEFAULT 2,
    status INTEGER DEFAULT 1,
    user_type INTEGER DEFAULT 2,
    last_login_time TIMESTAMP,
    last_login_ip VARCHAR(50),
    tenant_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    remark VARCHAR(500)
);
