# 充电站服务配置文件
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.config.client.ConfigClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    name: evcs-station
  
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/evcs_mgr?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Station
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0
          max-wait: 2000ms

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# 服务端口
server:
  port: 8082

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.evcs.station.entity

# 日志配置
logging:
  level:
    com.evcs.station.mapper: debug
    com.evcs.common.tenant: debug
    org.springframework.security: debug
    
# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# 多租户配置
evcs:
  tenant:
    # 启用多租户功能
    enabled: true
    # 租户ID字段名
    tenant-id-column: tenant_id
    # 忽略多租户的表
    ignore-tables:
      - sys_tenant
      - sys_user
      - sys_role
      - sys_permission
    # 默认租户ID（系统管理员）
    default-tenant-id: 1

# 充电站服务配置
station:
  # 附近充电站查询配置
  nearby:
    default-radius: 10  # 默认查询半径(公里)
    max-radius: 50      # 最大查询半径(公里)
    default-limit: 20   # 默认返回数量
    max-limit: 100      # 最大返回数量
  
  # 充电桩离线检测配置
  charger:
    offline-threshold: 5  # 离线检测阈值(分钟)
    heartbeat-interval: 30 # 心跳间隔(秒)
    
  # 导入导出配置
  import:
    batch-size: 100     # 批量导入大小
    max-records: 1000   # 最大导入记录数