#!/bin/bash

# EVCS项目Git预提交检查脚本
# 确保代码质量符合项目规范，支持AI编程助手生成的代码

echo "🔍 开始执行预提交检查..."

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 函数：打印带颜色的消息
print_message() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

# 函数：检查命令是否存在
check_command() {
    if ! command -v $1 &> /dev/null; then
        print_message $RED "❌ 错误: $1 命令未安装"
        return 1
    fi
    return 0
}

# 函数：检查是否为AI生成代码
check_ai_generated_code() {
    local file=$1
    if [ -f "$file" ]; then
        # 检查是否包含AI代码生成的特征
        if grep -q -E "(Generated by (Claude|Copilot|AI)|AI-(generated|assisted)|# (Generated|Created) by" "$file"; then
            return 0
        fi
    fi
    return 1
}

# 1. 检查必要的工具
print_message $YELLOW "🔧 检查必要的工具..."
check_command gradle || exit 1
check_command git || exit 1

# 2. 统计AI生成代码文件
print_message $BLUE "🤖 统计AI生成的代码文件..."
ai_files_count=0
total_files_count=0

# 检查Java文件
java_files=$(find . -name "*.java" -not -path "./build/*" -not -path "./.gradle/*" -not -path "./.git/*")
for file in $java_files; do
    total_files_count=$((total_files_count + 1))
    if check_ai_generated_code "$file"; then
        ai_files_count=$((ai_files_count + 1))
    fi
done

if [ $total_files_count -gt 0 ]; then
    ai_percentage=$((ai_files_count * 100 / total_files_count))
    print_message $BLUE "📊 AI生成代码: $ai_files_count/$total_files_count ($ai_percentage%)"
else
    print_message $BLUE "📊 未发现Java文件"
fi

# 3. 运行代码质量检查
print_message $YELLOW "🔍 运行代码质量检查..."

# 检查是否有代码质量检查插件
if ./gradlew tasks --all | grep -q "checkstyleMain"; then
    print_message $YELLOW "📝 检查代码格式 (Checkstyle)..."
    if ! ./gradlew checkstyleMain > /dev/null 2>&1; then
        print_message $RED "❌ 代码格式检查失败"
        echo "请运行 ./gradlew checkstyleMain 查看详细错误"
        echo "参考规范: docs/02-development/CODE-QUALITY-CHECKLIST.md"
        exit 1
    else
        print_message $GREEN "✅ 代码格式检查通过"
    fi
else
    print_message $YELLOW "⚠️  Checkstyle插件未配置，跳过代码格式检查"
fi

if ./gradlew tasks --all | grep -q "pmdMain"; then
    print_message $YELLOW "📝 检查代码质量 (PMD)..."
    if ! ./gradlew pmdMain > /dev/null 2>&1; then
        print_message $RED "❌ PMD代码质量检查失败"
        echo "请运行 ./gradlew pmdMain 查看详细错误"
        exit 1
    else
        print_message $GREEN "✅ PMD代码质量检查通过"
    fi
else
    print_message $YELLOW "⚠️  PMD插件未配置，跳过代码质量检查"
fi

if ./gradlew tasks --all | grep -q "spotbugsMain"; then
    print_message $YELLOW "🐛 检查静态代码分析 (SpotBugs)..."
    if ! ./gradlew spotbugsMain > /dev/null 2>&1; then
        print_message $RED "❌ SpotBugs检查失败"
        echo "请运行 ./gradlew spotbugsMain 查看详细错误"
        exit 1
    else
        print_message $GREEN "✅ SpotBugs检查通过"
    fi
else
    print_message $YELLOW "⚠️  SpotBugs插件未配置，跳过静态代码分析"
fi

# 4. 运行单元测试
print_message $YELLOW "🧪 运行单元测试..."
if ! ./gradlew test > /dev/null 2>&1; then
    print_message $RED "❌ 单元测试失败"
    echo "请运行 ./gradlew test 查看详细错误"
    exit 1
else
    print_message $GREEN "✅ 单元测试通过"
fi

# 5. 检查代码覆盖率
print_message $YELLOW "📊 检查代码覆盖率..."
if ./gradlew tasks --all | grep -q "jacocoTestReport"; then
    ./gradlew jacocoTestReport > /dev/null 2>&1

    # 检查覆盖率是否达标
    COVERAGE_THRESHOLD=80
    if [ -f "build/reports/jacoco/test/html/index.html" ]; then
        COVERAGE=$(grep -o "Total.*[0-9]*%" build/reports/jacoco/test/html/index.html | grep -o '[0-9]*' | head -1)

        if [ -n "$COVERAGE" ] && [ "$COVERAGE" -ge "$COVERAGE_THRESHOLD" ]; then
            print_message $GREEN "✅ 代码覆盖率: ${COVERAGE}% (阈值: ${COVERAGE_THRESHOLD}%)"
        else
            print_message $YELLOW "⚠️  代码覆盖率: ${COVERAGE}% (阈值: ${COVERAGE_THRESHOLD}%)"
            print_message $YELLOW "   建议提高测试覆盖率到${COVERAGE_THRESHOLD}%以上"
        fi
    else
        print_message $YELLOW "⚠️  无法获取覆盖率数据"
    fi
else
    print_message $YELLOW "⚠️  JaCoCo插件未配置，跳过覆盖率检查"
fi

# 6. 检查微服务架构规范
print_message $YELLOW "🏗️ 检查微服务架构规范..."
architecture_violations=0

# 检查跨服务数据库访问
cross_db_patterns=(
    "Autowired.*Repository.*"
    "@Autowired.*[A-Za-z]*Repository"
    "private.*[A-Za-z]*Repository.*"
)

for pattern in "${cross_db_patterns[@]}"; do
    if grep -r -E "$pattern" --include="*.java" evcs-*/src/main/java/ 2>/dev/null | grep -v evcs-common; then
        architecture_violations=$((architecture_violations + 1))
        print_message $RED "   ❌ 发现可能的跨服务数据库访问"
    fi
done

# 检查硬编码敏感信息
sensitive_patterns=(
    "password\s*=\s*['\"][^'\"]+['\"]"
    "secret\s*=\s*['\"][^'\"]+['\"]"
    "jwt.*secret"
    "alipay.*appId"
    "wechat.*mchId"
)

found_secrets=false
for pattern in "${sensitive_patterns[@]}"; do
    if grep -r -i -E "$pattern" --include="*.java" --include="*.yml" --include="*.yaml" --include="*.properties" evcs-*/src/main/ 2>/dev/null; then
        print_message $RED "   ❌ 发现可能的硬编码敏感信息: $pattern"
        found_secrets=true
        architecture_violations=$((architecture_violations + 1))
    fi
done

if [ $architecture_violations -eq 0 ]; then
    print_message $GREEN "✅ 微服务架构规范检查通过"
else
    print_message $RED "❌ 发现 $architecture_violations 个架构违规"
    echo "请参考: docs/02-development/AI-ASSISTANT-GUIDELINES.md"
    exit 1
fi

# 7. 检查Docker配置
print_message $YELLOW "🐳 检查Docker配置..."
docker_issues=0

# 检查是否有Dockerfile.simple文件（已删除，但双重确认）
if find . -name "Dockerfile.simple" -type f 2>/dev/null; then
    print_message $RED "   ❌ 发现已删除的Dockerfile.simple文件"
    docker_issues=$((docker_issues + 1))
fi

# 检查Dockerfile配置
for service_dir in evcs-*/; do
    if [ -f "$service_dir/Dockerfile" ]; then
        service_name=$(basename "$service_dir")

        # 检查是否使用正确的基础镜像
        if grep -q "eclipse-temurin:21-jre-alpine" "$service_dir/Dockerfile"; then
            print_message $GREEN "   ✅ $service_name 使用正确的运行时镜像"
        else
            print_message $YELLOW "   ⚠️  $service_name 可能未使用标准运行时镜像"
        fi

        # 检查是否使用统一的Gradle版本
        if grep -q "gradle:8.11-jdk21-alpine" "$service_dir/Dockerfile"; then
            print_message $GREEN "   ✅ $service_name 使用正确的构建镜像"
        else
            print_message $YELLOW "   ⚠️  $service_name 可能未使用标准构建镜像"
        fi
    fi
done

if [ $docker_issues -eq 0 ]; then
    print_message $GREEN "✅ Docker配置检查通过"
else
    print_message $RED "❌ 发现 $docker_issues 个Docker配置问题"
    exit 1
fi

# 8. 检查文件大小限制
print_message $YELLOW "📏 检查文件大小限制..."
MAX_FILE_SIZE=10485760  # 10MB

large_files=$(find . -type f -not -path "./.git/*" -not -path "./build/*" -not -path "./.gradle/*" -not -path "./docs/archive/*" -size +${MAX_FILE_SIZE}c)

if [ -n "$large_files" ]; then
    print_message $RED "❌ 发现大文件 (>10MB):"
    echo "$large_files" | while read file; do
        size=$(du -h "$file" | cut -f1)
        print_message $RED "   $file ($size)"
    done
    exit 1
else
    print_message $GREEN "✅ 没有发现超大文件"
fi

# 9. 检查提交信息格式（如果有提交）
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    print_message $YELLOW "📝 检查提交信息格式..."

    commit_msg=$(git log -1 --pretty=%B)

    # 检查提交信息是否包含必要信息
    if [[ ! "$commit_msg" =~ ^(feat|fix|docs|style|refactor|test|chore)(\([^)]*\))?: .+ ]]; then
        print_message $RED "❌ 提交信息格式不符合规范"
        echo "格式要求: type(scope): description"
        echo "类型: feat, fix, docs, style, refactor, test, chore"
        exit 1
    else
        print_message $GREEN "✅ 提交信息格式正确"
    fi
fi

# 10. 生成质量报告摘要
print_message $BLUE "📋 质量检查摘要"
print_message $BLUE "   - Java文件总数: $total_files_count"
print_message $BLUE "   - AI生成代码: $ai_files_count ($ai_percentage%)"
if [ $architecture_violations -eq 0 ]; then
    print_message $BLUE "   - 架构规范: ✅ 通过"
else
    print_message $BLUE "   - 架构规范: ❌ $architecture_violations 个问题"
fi
if [ $docker_issues -eq 0 ]; then
    print_message $BLUE "   - Docker配置: ✅ 通过"
else
    print_message $BLUE "   - Docker配置: ❌ $docker_issues 个问题"
fi

print_message $GREEN "🎉 所有预提交检查通过！"
echo "代码符合EVCS项目规范，可以提交到Git仓库。"
echo ""
echo "📚 相关文档:"
echo "   - AI助手规范: docs/02-development/AI-ASSISTANT-GUIDELINES.md"
echo "   - 代码质量清单: docs/02-development/CODE-QUALITY-CHECKLIST.md"
echo "   - 项目结构: docs/operations/PROJECT-STRUCTURE.md"