# 通用测试配置模板
# 各个模块可以根据需要覆盖此配置

spring:
  main:
    allow-bean-definition-overriding: true

  # 禁用不必要的自动配置以加快测试速度
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.config.client.ConfigClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # 禁用 Spring Cloud
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      import-check:
        enabled: false

  # 使用内存数据库进行测试
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

# 禁用 Eureka
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.evcs: debug
    org.springframework.test: warn
    org.springframework.web: warn
    org.springframework.security: warn

# 多租户配置
evcs:
  tenant:
    enabled: true
    tenant-id-column: tenant_id
    ignore-tables:
      - sys_tenant
      - sys_user
      - sys_role
      - sys_permission
      - sys_dict_type
      - sys_dict_data
    default-tenant-id: 1
